export interface IOrder {
  id: number,
  store_id: number,
  costumer: string,
  costumer_group_id: number,
  currency_id: number,
  first_name: string,
  last_name: string,
  email: string,
  country: string,
  city: string,
  telephone: string,
  status_id: number,
  total: string,
  checkoutDelivery: string,
  checkoutDeliveryAddress: string,
  checkoutPayment: string,
  checkoutRecipient: string,
  recipient: string,
  recipientFirstName: string,
  recipientLastName: string,
  recipientPhone: string,
  delivery_id: number,
  created_at: string,
  updated_at: string
}
