export const ALL_PERMISSIONS = [
  { label: "Manage attribytes", key: "manage_attribytes" },
  { label: "Manage attribyte descriptions", key: "manage_attribytedescriptions" },
  { label: "Manage attribyte groups", key: "manage_attribytegroups" },
  { label: "Manage attribyte group descriptions", key: "manage_attribytegroupdescriptions" },
//   { label: "Manage ", key: "manage_auths" },
  { label: "Manage roles", key: "manage_roles" },
  { label: "Manage users", key: "manage_users" },
  { label: "Manage telegram bots", key: "manage_telegrambots" },
  { label: "Manage categorys", key: "manage_categorys" },
  { label: "Manage category descriptions", key: "manage_categorydescriptions" },
  { label: "Manage collections", key: "manage_collections" },
  { label: "Manage collection descriptions", key: "manage_collectiondescriptions" },
  { label: "Manage albums", key: "manage_albums" },
  { label: "Manage image descriptions", key: "manage_imagedescriptions" },
  { label: "Manage images", key: "manage_imagess" },
  { label: "Manage languagess", key: "manage_languagess" },
  { label: "Manage lenght classs", key: "manage_lenghtclasss" },
  { label: "Manage lenght class descriptions", key: "manage_lenghtclassdescriptions" },
  { label: "Manage manufacturers", key: "manage_manufacturers" },
  { label: "Manage manufacturer descriptions", key: "manage_manufacturerdescriptions" },
  { label: "Manage options", key: "manage_options" },
  { label: "Manage option descriptions", key: "manage_optiondescriptions" },
  { label: "Manage option keys", key: "manage_optionkeys" },
  { label: "Manage option key descriptions", key: "manage_optionkeydescriptions" },
  { label: "Manage product options", key: "manage_productoptions" },
  { label: "Manage produc optoption keys", key: "manage_productoptionkeys" },
  { label: "Manage products", key: "manage_products" },
  { label: "Manage product descriptions", key: "manage_productdescriptions" },
  { label: "Manage product disconts", key: "manage_productdisconts" },
  { label: "Manage product images", key: "manage_productimages" },
  { label: "Manage product relateds", key: "manage_productrelateds" },
  { label: "Manage product rewards", key: "manage_productrewards" },
  { label: "Manage product specials", key: "manage_productspecials" },
  { label: "Manage product promotions", key: "manage_productpromotions" },
  { label: "Manage product attribytes", key: "manage_productattribytes" },
  { label: "Manage product categoriess", key: "manage_productcategoriess" },
  { label: "Manage product collections", key: "manage_productcollections" },
  { label: "Manage stockstatus", key: "manage_stockstatuss" },
  { label: "Manage promotions", key: "manage_promotions" },
  { label: "Manage promotion descriptions", key: "manage_promotiondescriptions" },
  { label: "Manage reviews", key: "manage_reviews" },
  { label: "Manage taxclass", key: "manage_taxclasss" },
  { label: "Manage taxrates", key: "manage_taxrates" },
  { label: "Manage taxrules", key: "manage_taxrules" },
  { label: "Manage blocks", key: "manage_blocks" },
  { label: "Manage block descriptions", key: "manage_blockdescriptions" },
  { label: "Manage block medias", key: "manage_blockmedias" },
  { label: "Manage menus", key: "manage_menus" },
  { label: "Manage menu descriptions", key: "manage_menudescriptions" },
  { label: "Manage pages", key: "manage_pages" },
  { label: "Manage page descriptions", key: "manage_pagedescriptions" },
  { label: "Manage weight classs", key: "manage_weightclasss" },
  { label: "Manage weight class descriptions", key: "manage_weightclassdescriptions" },
];
